/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopsWorkshopIdRouteImport } from './routes/workshops.$workshopId'
import { Route as WorkshopsNewRouteImport } from './routes/workshops.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsWorkshopIdRoute = WorkshopsWorkshopIdRouteImport.update({
  id: '/workshops/$workshopId',
  path: '/workshops/$workshopId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsNewRoute = WorkshopsNewRouteImport.update({
  id: '/workshops/new',
  path: '/workshops/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workshops/$workshopId': typeof WorkshopsWorkshopIdRoute
  '/workshops/new': typeof WorkshopsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workshops/$workshopId': typeof WorkshopsWorkshopIdRoute
  '/workshops/new': typeof WorkshopsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workshops/$workshopId': typeof WorkshopsWorkshopIdRoute
  '/workshops/new': typeof WorkshopsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workshops/$workshopId' | '/workshops/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workshops/$workshopId' | '/workshops/new'
  id: '__root__' | '/' | '/workshops/$workshopId' | '/workshops/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkshopsWorkshopIdRoute: typeof WorkshopsWorkshopIdRoute
  WorkshopsNewRoute: typeof WorkshopsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/$workshopId': {
      id: '/workshops/$workshopId'
      path: '/workshops/$workshopId'
      fullPath: '/workshops/$workshopId'
      preLoaderRoute: typeof WorkshopsWorkshopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/new': {
      id: '/workshops/new'
      path: '/workshops/new'
      fullPath: '/workshops/new'
      preLoaderRoute: typeof WorkshopsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkshopsWorkshopIdRoute: WorkshopsWorkshopIdRoute,
  WorkshopsNewRoute: WorkshopsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
